using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.Entity;

namespace B_PowerWin
{
    public partial class Form1 : GUI.FormBase
    {

        public Form1()
        {
            InitializeComponent();
            initObj();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            B_PowerWin.AppDbContext dbContext = new B_PowerWin.AppDbContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.SecPrincipalUsers.LoadAsync().ContinueWith(loadTask =>
                    {
                    // Bind data to control when loading complete
                    secPrincipalUsersBindingSource.DataSource = dbContext.SecPrincipalUsers.Local.ToBindingList();
                    }, 
                   System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext()
              );
            
        }

        private void initObj()
        {
            //usersBS.DataSource = MySession.Session.Database.SecPrincipalUsers.Local;
            //userGC.DataSource = usersBS;
            testSimpleButton.Click += (s, e) => {
                DB.SeedDatabase.SeedUILabels(MySession.Session.Database);
                DB.SeedDatabase.SeedEnumTable(MySession.Session.Database);
            };

            
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            var frm = new GUI.UILabelManagerFrm() { WindowState = FormWindowState.Maximized };
            frm.Show();
        }
    }
}
