// <auto-generated />
namespace B_PowerWin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init_0040 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_0040));
        
        string IMigrationMetadata.Id
        {
            get { return "202111201610424_init_0040"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
