// <auto-generated />
namespace B_PowerWin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init_0009 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_0009));
        
        string IMigrationMetadata.Id
        {
            get { return "202110252223566_init_0009"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
